### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by WorldNomads** [nehalist/gitsta#10]
Markdown allows for tables but this CSS template doesn't appear to format for them ... unless I"m missing something?

**Comment by nehalist** [comment]
What kind of html is produced by your markdown for tables?

Default tables should be automatically get modified to get all necessary classes for bootstrap tables (especially the `table` class). This modification is a content filter, located here; https://github.com/nehalist/gitsta/blob/master/functions.php#L149
