### ISSUE TITLE
Map markers from Google Maps are not visible

### ISSUE THREAD

**Issue by pwittchen** [nehalist/gitsta#11]
Hi,

Google Maps markers are not visible on the blog with this theme :-(. I tried to add map with [Google Maps Builder](https://wordpress.org/plugins/google-maps-builder/) plugin and via tools like [map-embed.com](http://www.map-embed.com/). In both cases markers are not visible on the map. I had API key added properly and map is visible. Markers are visible with default Worpdress themes, but I have no idea why they're are not visible with gitsta theme. I suppose there may be conflicts in JavaScript code, but I couldn't find exact problem or solution. It may be related to third-party libraries using JavaScript in this theme or custom JavaScript code written for this theme. Do you know, how to fix this?

Regards,
Piotr

**Comment by nehalist** [comment]
Hey,

could you please provide the code you used to implement the map? :)

Thanks!

**Comment by pwittchen** [comment]
I simply installed this plugin: https://wordimpress.com/plugins/maps-builder-pro/ (free version).
Then, in Dashboard (admin panel) on the left menu you have an option "Google Maps". I created single map. I clicked map preview. Link to the preview looks like that:

http://addres.of.the.blog/?post_type=google_maps&p=MAP_ID&preview=true

I can also use shortcode in the pages and posts, which looks like that:
```
[google_maps id="MAP_ID"]
```

`MAP_ID` is a number.

My dashboard looks like that:

![dashboard](https://cloud.githubusercontent.com/assets/695319/17037807/f569f946-4f92-11e6-98a0-70e7626b57fd.png)

but preview looks like that (as you can see, **there's no marker**):

![preview](https://cloud.githubusercontent.com/assets/695319/17037811/fe3ea472-4f92-11e6-9918-5bc86ddc70fd.png)

Marker is visible in default wordpress themes, so this bug is related to the gitsta theme.

**Comment by nehalist** [comment]
Thanks for this detailed answer! I'll take a look at it over the weekend! :)

**Comment by pwittchen** [comment]
Ok, thanks for your help and quick response!
I'll wait for the next update. :)

**Comment by nehalist** [comment]
[Last release](https://github.com/nehalist/gitsta/releases/tag/1.4.2) should fix the problem.

These markers doesn't like it when the map container has a `max-width`. Kinda weird, but well...

**Comment by pwittchen** [comment]
I've tested this fix a few seconds ago and it works for me. Thanks!
