### ISSUE TITLE
Image alignment when Caption present

### ISSUE THREAD

**Issue by addshore** [nehalist/gitsta#6]
I just tried adding some comments to some images on a blog post where one image was meant to be aligned right and the other centre.
Once the captions had been added the preview showed the images aligned left instead of in their respected places.
If the captions are then removed the image returned to its correct position.

**Comment by nehalist** [comment]
What exactly do you mean by "adding comments to images"? A screenshot of the issue would be also very helpful :)

**Comment by addshore** [comment]
See the screenshots below (I hope they help!)

So this is the article with no caption and image alligned right
![wp-nocap](https://cloud.githubusercontent.com/assets/3308769/6992939/c62ffad6-dadb-11e4-8bbb-c4852e2f1c92.JPG)
This is where I am adding the caption
![wp-addingcap](https://cloud.githubusercontent.com/assets/3308769/6992941/cf155b50-dadb-11e4-8b84-27cdbccac1a3.JPG)
In the edit screen everything is then still alligned correctly
![wp-capinedit](https://cloud.githubusercontent.com/assets/3308769/6992940/c9e1880c-dadb-11e4-943a-947514daecb4.JPG)
When previewing the image and caption shift over to the left (even when they should be right or centre)
![wp-capinpreview](https://cloud.githubusercontent.com/assets/3308769/6992943/d31c1e6e-dadb-11e4-96de-124dd5486921.JPG)

The HTML in the final screenshot for the image is as follows:

      <div id="attachment_46" style="width: 266px" class="wp-caption alignright"><a href="http://i1.wp.com/addshore.com/wp-content/uploads/2015/04/cloud-10-256x256.png"><img class="wp-image-46 size-full img-thumbnail img-responsive" src="http://i1.wp.com/addshore.com/wp-content/uploads/2015/04/cloud-10-256x256.png?resize=256%2C256" alt="A cloud" width="256" height="256"></a><p class="wp-caption-text">This is a caption</p></div>

**Comment by nehalist** [comment]
Thanks for the screenshots! Will take a look at it within the next days!

**Comment by addshore** [comment]
Awesome :)

**Comment by addshore** [comment]
Thanks!

**Comment by nehalist** [comment]
You're welcome :)

**Comment by addshore** [comment]
Just wondering how does this measure up against what gets released at https://wordpress.org/themes/gitsta/ ?

I see you just tagged 1.3.4 but apparently thats on 1.3.6 and the source is somewhere else? https://themes.trac.wordpress.org/log/gitsta/

Quite confused :/

**Comment by nehalist** [comment]
I've uploaded the theme already right after pushing it to GitHub, but it always takes some time until they release it on wordpress.org (around 1 - 2 days). But you can also download it here now: https://github.com/nehalist/gitsta/releases/tag/v1.3.6
