### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by addshore** [nehalist/gitsta#9]
This may be a personal preference but as the theme is trying to be github like could the code blocks in posts not also be more like github.
Personally I think the current ones are very in your face (see below)

![image](https://cloud.githubusercontent.com/assets/3308769/7100942/479a7fc0-e035-11e4-82f9-51674a2417c4.png)

I much prefer the simplicity of code block below

```php
</php
//Test
$foo = 'barbar';
var_dump( $foo );
```

What do you think? (Of course I'm not looking for code highlighting, there are plugins to do that....)

**Comment by nehalist** [comment]
This is indeed a personal preference and not an issue. I, for example, like line numbers a lot :) But if you want to get rid of the current code block style und switch to something more simple, just remove line 147-158 in `functions.php` and change the stylesheets of the `pre` tag (line 101 in `style.css`) to something like

```
pre {
    background-color: #cecece;
    border: 0 !important;
}
```

**Comment by addshore** [comment]
Awesome! Thanks!
Was wondering if there could be a switch in the theme settings, but this is just as good for me!
